# Generated by Django 4.1.7 on 2023-04-27 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pulled_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 3, 22, 53, 884823, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
