# Generated by Django 4.2.5 on 2023-10-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0003_alter_item_pulled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='major',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deferred_items', to='hat.meeting'),
        ),
        migrations.AddField(
            model_name='item',
            name='submitted_meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hat.meeting'),
        ),
    ]
