# Generated by Django 4.2.5 on 2023-10-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0004_meeting_item_finished_item_major_item_meeting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='submitted_meeting',
        ),
        migrations.AlterField(
            model_name='item',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hat.meeting'),
        ),
    ]
