# Generated by Django 4.2.5 on 2023-10-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0005_remove_item_submitted_meeting_alter_item_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='previous_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hat.meeting'),
        ),
    ]
