# Generated by Django 5.2.6 on 2025-09-10 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hat", "0006_item_previous_meeting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveField(
            model_name="item",
            name="pulled",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
